language: node_js

node_js:
  - "10"

addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  npm: true
  directories:
    - ~/.cache

install:
  - yarn install --frozen-lockfile

script:
  - yarn lint
  - yarn build
  - yarn start &
  - sleep 5
  - yarn test
