language: node_js

node_js:
  - "11"

addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  npm: true
  directories:
    - ~/.cache

install:
  - npm ci

script:
  - yarn lint
  - yarn test
  - yarn build
